# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    architecture: 'x64'

# Invoke Azure Function
# Invoke an Azure Function as a part of your pipeline.
- task: InvokeRESTAPI@1
  inputs:
    connectionType: connectedServiceName
    serviceConnection: https://oneweekfuncapp.azurewebsites.net/api/HttpTrigger
    method: 'GET' 
    waitForCompletion: 'true' 
    #successCriteria: # Optional